species:
  source:
    name: pine
  target:
    name: spruce

genome:
  pine: resources/genome/coverage_purged_soft_pine-hifi-27cells-no-purge_m250-r500_manual2.purged.fa.gz
  spruce: resources/genome/pabies-2.0_chromosomes_and_unplaced.fa.gz

cds:
  type: nucl
  pine: resources/cds/hq_transcripts_fixed_headers.fasta.transdecoder.cds
  spruce: resources/cds/Spruce_all_hq_transcripts_clean_headers.fasta.transdecoder.cds

gff:
  pine: resources/gmap/pine-isoseq_vs_pine.gff3.uniq
  spruce: resources/gmap/spruce-isoseq_vs_spruce.gff3.uniq

gff_to_bed:
  feature: mRNA
  name_attr: Name

# Set the name regex to null or an empty string in order to
# disable the cleaning of fasta headers.
clean_fasta_headers:
  name_regex:
    spruce: 'transcript_\d+'
    pine: 'UnnamedSample_HQ_transcript_\d+'
